logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log
spring:
  application:
    name: Petistaan
  datasource:
    url: jdbc:postgresql://localhost:5432/petistaan
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  profiles:
    active: prod

springdoc:
  api-docs:
    path: /documentation
  swagger-ui:
    path: /swagger.html
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, env, configprops
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
  message: "Subscribe Abhishek Verma to learn Java"
