logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log
spring:
  application:
    name: PetistaanClient
  datasource:
    url: jdbc:postgresql://localhost:5432/petistaan
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  profiles:
    active: prod
  boot:
    admin:
      client:
        url: http://localhost:9091 
        instance:
          service-base-url: http://localhost:8080
          metadata:
            instance-id: unique-client-id

server:
  servlet:
    context-path: /petistaan		
springdoc:
  api-docs:
    path: /documentation
  swagger-ui:
    path: /swagger.html
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    configprops:
      show-values: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
  message: "Subscribe Abhishek Verma to learn Java"
